name: Build and deploy backend to Azure Web App - ps-performance-feedback-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install --omit=dev

      - name: Deploy backend to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ps-performance-feedback-api'
          slot-name: 'Production'
          package: './backend'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B163A2B2ED9A446BA28A5A9EADE9B515 }}
